name: Redeploy on Vercel

on:
  schedule:
  # Run the workflow every hour
  - cron: "0 */1 * * *"
  # Allows Running the workflow manually from the Actions tab
  workflow_dispatch:
    
jobs:
  rebuild-and-redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger vercel deploy hook to rebuild the app with the new data
        run: curl -X POST -d {} ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
